language: python
python:
  - "3.6"
  - "3.7"
os:
  - linux
  - osx
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - make test
  - 